### ISSUE TITLE
takes me to statistics screen i click on start duel (link evolution)

### ISSUE THREAD

**Issue by astroavenger9** [pixeltris/Lotd#10]
what the title says

**Comment by pixeltris** [comment]
Oh whoops someone was asking about going to that screen, I guess I forgot to recompile after I removed that. I've updated the zip and it should now go to the duel screen when pressed.

**Comment by astroavenger9** [comment]
ok i'll re-download and try agian.

**Comment by astroavenger9** [comment]
ok i was able to start a dual, problem seems to be fixed. thanks.

**Comment by pixeltris** [comment]
Great.

**Comment by astroavenger9** [comment]
ran into another problem. when i put starting player to opponent i still go first.
