### ISSUE TITLE
Master Duel

### ISSUE THREAD

**Issue by fuwafoowa** [pixeltris/Lotd#18]
Any plans for Yu-Gi-Oh Master Duel?

**Comment by pixeltris** [comment]
I'm working on something but it'll be on a separate repo. I'll link it when it's up.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/YgoMaster the code is up. It isn't quite a duel starter like this project, but you can start custom duels with it. I don't have any plans at this time to make a proper UI for it.
